version: '3'

volumes:
  pgdata:
  pgadmin-data:
  tracing-data:

networks:
  dbnetwork:
    name: database-network
    driver: bridge
    external: false
  tracing_network:
    name: tracing-network
    driver: bridge
    external: false

services:
  database:
    image: postgres:15.4
    container_name: deadjokes_database
    tty: true
    env_file:
      - .env
    networks:
      - dbnetwork
    ports:
      - '15432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./.data/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: deadjokes_pgadmin
    tty: true
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - dbnetwork
    ports:
      - '15433:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: deadjokes_jaeger
    tty: true
    env_file:
      - .env
    networks:
      - tracing_network
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
      - '5778:5778'
    volumes:
      - tracing-data:/tmp
    restart: unless-stopped
