version: '3'

services:
  api:
    image: deadjokes-api
    container_name: deadjokes_api
    env_file:
      - .env
    depends_on:
      - database
      - logstash
      - jaeger-collector
    networks:
      - dbnetwork
      - elastic_network
    ports:
      - '4343:4343'
    volumes:
      - '${XDG_DATA_HOME}/deadjokes-api/:/root/.local/share/deadjokes-api/:rw'
    restart: on-failure
