version: '3'

volumes:
  elasticsearch-data:
    driver: local
  logstash_data:
    driver: local
  kibana-data:
    driver: local

networks:
  elastic_network:
    name: elastic-network
    driver: bridge
    external: false

services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    container_name: deadjokes_elasticsearch
    networks:
      - elastic_network
    volumes:
      - 'elasticsearch-data:/bitnami/elasticsearch'

  logstash:
    image: docker.io/bitnami/logstash:7
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    volumes:
      - 'logstash_data:/bitnami'

  kibana:
    image: docker.io/bitnami/kibana:7
    container_name: deadjokes_kibana
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - elastic_network
    volumes:
      - 'kibana-data:/bitnami/kibana'

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.50
    container_name: deadjokes_jaeger_collector
    env_file:
      - .env
    depends_on:
      - elasticsearch
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    networks:
      - elastic_network
    ports:
      - '9411:9411'
      - '14250:14250'
      - '14267:14267'
      - '14268:14268'
      - '14269:14269'
    restart: on-failure

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.50
    container_name: deadjokes_jaeger_agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    env_file:
      - .env
    depends_on:
      - jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    networks:
      - elastic_network
    ports:
      - '5778:5778'
      - '6831:6831'
      - '6832:6832'
    restart: on-failure

  jaeger-query:
    image: jaegertracing/jaeger-query:1.50
    container_name: deadjokes_jaeger_query
    env_file:
      - .env
    depends_on:
      - jaeger-agent
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    networks:
      - elastic_network
    ports:
      - '16686:16686'
      - '16687:16687'
    restart: on-failure
