version: '3'

volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local

networks:
  dbnetwork:
    name: database-network
    driver: bridge
    external: false

services:
  database:
    image: postgres:15.4
    container_name: deadjokes_database
    tty: true
    env_file:
      - .env
    networks:
      - dbnetwork
    ports:
      - '15432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
      - './.data/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro'

  pgadmin:
    image: dpage/pgadmin4
    container_name: deadjokes_pgadmin
    tty: true
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - dbnetwork
    ports:
      - '15433:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin/'
